@echo off
setlocal EnableDelayedExpansion
rem ============================================================================
rem  RANDOM WORLD - one-click seed randomizer + launcher (Windows)
rem  ---------------------------------------------------------------------------
rem  Double-click this file BEFORE playing (while HOI4 is closed):
rem    1. it writes a fresh random world seed into the mod;
rem    2. it starts Hearts of Iron IV (if the path below is correct).
rem  Result: every launch of the game = a different world, already visible
rem  in the country-selection lobby.
rem
rem  Why a restart at all? The game engine parses mod files exactly once,
rem  at application launch - no external tool can change a world inside a
rem  running game. This script just makes the restart painless.
rem
rem  The file must stay in the MOD ROOT folder (next to descriptor.mod).
rem ============================================================================

set "SEEDFILE=%~dp0common\scripted_effects\rw_world_seed.txt"

if not exist "%SEEDFILE%" (
    echo ERROR: cannot find common\scripted_effects\rw_world_seed.txt
    echo Keep this script in the mod root folder, next to descriptor.mod.
    pause
    exit /b 1
)

rem Random seed 0-499: kept small on purpose, so the in-game "seed burn"
rem loop stays instant and safely under engine loop limits.
set /a SEED=%RANDOM% %% 500

> "%SEEDFILE%" echo # Auto-generated by randomize_seed_and_play.bat - edits made here by hand
>> "%SEEDFILE%" echo # survive only until the next run of that script.
>> "%SEEDFILE%" echo # Current world seed: %SEED%
>> "%SEEDFILE%" echo rw_set_world_seed = {
>> "%SEEDFILE%" echo 	set_variable = { global.rw_world_seed = %SEED% }
>> "%SEEDFILE%" echo }

echo.
echo   New world seed written: %SEED%
echo   (note it down if you may want to replay this exact world later)
echo.

rem --- Optional auto-launch. Fix the path if your game lives elsewhere. ------
set "GAME_EXE=C:\Program Files (x86)\Steam\steamapps\common\Hearts of Iron IV\hoi4.exe"

if exist "%GAME_EXE%" (
    echo   Starting Hearts of Iron IV...
    echo   ^(launching hoi4.exe directly keeps the mods of your LAST-USED
    echo   playset active; if mods seem missing, start the game through the
    echo   normal launcher instead - the seed is already saved either way^)
    start "" "%GAME_EXE%"
) else (
    echo   hoi4.exe not found at:
    echo     %GAME_EXE%
    echo   Either fix the GAME_EXE path inside this script, or just start
    echo   the game yourself - the new seed is already saved.
)
echo.
pause
